---
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports: ['${NGINX_PORT:-1234}:80']
    volumes: [build:/var/www/html/public/build]
    networks: [laravel]
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes: [build:/var/www/html/public/build]
    networks: [laravel]
    environment:
      - DB_CONNECT=${DB_CONNECT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - APP_LOCALE=${APP_LOCALE}
      - APP_FALLBACK_LOCALE=${APP_FALLBACK_LOCALE}
      - APP_FAKER_LOCALE=${APP_FAKER_LOCALE}
      - APP_MAINTENANCE_DRIVER=${APP_MAINTENANCE_DRIVER}
      - PHP_CLI_SERVER_WORKERS=${PHP_CLI_SERVER_WORKERS}
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - LOG_STACK=${LOG_STACK}
      - LOG_DEPRECATIONS_CHANNEL=${LOG_DEPRECATIONS_CHANNEL}
      - LOG_LEVEL=${LOG_LEVEL}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - SESSION_LIFETIME=${SESSION_LIFETIME}
      - SESSION_ENCRYPT=${SESSION_ENCRYPT}
      - SESSION_PATH=${SESSION_PATH}
      - SESSION_DOMAIN=${SESSION_DOMAIN}
      - BROADCAST_CONNECTION=${BROADCAST_CONNECTION}
      - FILESYSTEM_DISK=${FILESYSTEM_DISK}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - CACHE_STORE=${CACHE_STORE}
      - MEMCACHED_HOST=${MEMCACHED_HOST}
      - REDIS_CLIENT=${REDIS_CLIENT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_SCHEME=${MAIL_SCHEME}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_USE_PATH_STYLE_ENDPOINT=${AWS_USE_PATH_STYLE_ENDPOINT}
      - VITE_APP_NAME=${VITE_APP_NAME}
      - STATAMIC_LICENSE_KEY=${STATAMIC_LICENSE_KEY}
      - STATAMIC_PRO_ENABLED=${STATAMIC_PRO_ENABLED}
      - STATAMIC_STACHE_WATCHER=${STATAMIC_STACHE_WATCHER}
      - STATAMIC_STATIC_CACHING_STRATEGY=${STATAMIC_STATIC_CACHING_STRATEGY}
      - STATAMIC_REVISIONS_ENABLED=${STATAMIC_REVISIONS_ENABLED}
      - STATAMIC_GRAPHQL_ENABLED=${STATAMIC_GRAPHQL_ENABLED}
      - STATAMIC_API_ENABLED=${STATAMIC_API_ENABLED}
      - STATAMIC_GIT_ENABLED=${STATAMIC_GIT_ENABLED}
      - DEBUGBAR_ENABLED=${DEBUGBAR_ENABLED}
  db:
    image: postgres:latest
    environment: [POSTGRES_USER=postgres, POSTGRES_PASSWORD=example]
    volumes: [db:/var/lib/postgresql/data]
    networks: [laravel]
networks:
  laravel:
volumes:
  db:
  build:
