---
services:
  # nginx:
  #   build:
  #     context: ./docker/nginx
  #     dockerfile: Dockerfile
  #   ports: [80:80]
  #   volumes: [www:/var/www/html]
  #   depends_on: [php]
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    # expose: [9000]
    ports: [80:80, 443:443]
    volumes: [www:/var/www/html]
volumes:
  www:
