/* This file is generated by Ziggy. */
declare module "ziggy-js" {
    interface RouteList {
        "debugbar.openhandler": [];
        "debugbar.clockwork": [
            {
                name: "id";
            }
        ];
        "debugbar.assets.css": [];
        "debugbar.assets.js": [];
        "debugbar.cache.delete": [
            {
                name: "key";
            },
            {
                name: "tags";
            }
        ];
        "sanctum.csrf-cookie": [];
        "ignition.healthCheck": [];
        "ignition.executeSolution": [];
        "ignition.updateConfig": [];
        "statamic.cp.login": [];
        "statamic.cp.": [];
        "statamic.cp.logout": [];
        "statamic.cp.password.request": [];
        "statamic.cp.password.email": [];
        "statamic.cp.password.reset": [
            {
                name: "token";
            }
        ];
        "statamic.cp.password.reset.action": [];
        "statamic.cp.token": [];
        "statamic.cp.extend": [];
        "statamic.cp.unauthorized": [];
        "statamic.cp.impersonation.stop": [];
        "statamic.cp.index": [];
        "statamic.cp.dashboard": [];
        "statamic.cp.navigation.index": [];
        "statamic.cp.navigation.create": [];
        "statamic.cp.navigation.store": [];
        "statamic.cp.navigation.show": [
            {
                name: "navigation";
            }
        ];
        "statamic.cp.navigation.edit": [
            {
                name: "navigation";
            }
        ];
        "statamic.cp.navigation.update": [
            {
                name: "navigation";
            }
        ];
        "statamic.cp.navigation.destroy": [
            {
                name: "navigation";
            }
        ];
        "statamic.cp.navigation.blueprint.edit": [
            {
                name: "navigation";
            }
        ];
        "statamic.cp.navigation.blueprint.update": [
            {
                name: "navigation";
            }
        ];
        "statamic.cp.navigation.tree.index": [
            {
                name: "navigation";
            }
        ];
        "statamic.cp.navigation.tree.update": [
            {
                name: "navigation";
            }
        ];
        "statamic.cp.navigation.pages.update": [
            {
                name: "navigation";
            }
        ];
        "statamic.cp.navigation.pages.create": [
            {
                name: "navigation";
            }
        ];
        "statamic.cp.navigation.pages.edit": [
            {
                name: "navigation";
            },
            {
                name: "edit";
            }
        ];
        "statamic.cp.collections.index": [];
        "statamic.cp.collections.create": [];
        "statamic.cp.collections.store": [];
        "statamic.cp.collections.show": [
            {
                name: "collection";
            }
        ];
        "statamic.cp.collections.edit": [
            {
                name: "collection";
            }
        ];
        "statamic.cp.collections.update": [
            {
                name: "collection";
            }
        ];
        "statamic.cp.collections.destroy": [
            {
                name: "collection";
            }
        ];
        "statamic.cp.collections.scaffold": [
            {
                name: "collection";
            }
        ];
        "statamic.cp.collections.scaffold.create": [
            {
                name: "collection";
            }
        ];
        "statamic.cp.collections.blueprints.index": [
            {
                name: "collection";
            }
        ];
        "statamic.cp.collections.blueprints.create": [
            {
                name: "collection";
            }
        ];
        "statamic.cp.collections.blueprints.store": [
            {
                name: "collection";
            }
        ];
        "statamic.cp.collections.blueprints.show": [
            {
                name: "collection";
            },
            {
                name: "blueprint";
            }
        ];
        "statamic.cp.collections.blueprints.edit": [
            {
                name: "collection";
            },
            {
                name: "blueprint";
            }
        ];
        "statamic.cp.collections.blueprints.update": [
            {
                name: "collection";
            },
            {
                name: "blueprint";
            }
        ];
        "statamic.cp.collections.blueprints.destroy": [
            {
                name: "collection";
            },
            {
                name: "blueprint";
            }
        ];
        "statamic.cp.collections.blueprints.reorder": [
            {
                name: "collection";
            }
        ];
        "statamic.cp.collections.tree.index": [
            {
                name: "collection";
            }
        ];
        "statamic.cp.collections.tree.update": [
            {
                name: "collection";
            }
        ];
        "statamic.cp.collections.entries.index": [
            {
                name: "collection";
            }
        ];
        "statamic.cp.collections.entries.actions.run": [
            {
                name: "collection";
            }
        ];
        "statamic.cp.collections.entries.actions.bulk": [
            {
                name: "collection";
            }
        ];
        "statamic.cp.collections.entries.create": [
            {
                name: "collection";
            },
            {
                name: "site";
            }
        ];
        "statamic.cp.collections.entries.preview.create": [
            {
                name: "collection";
            },
            {
                name: "site";
            }
        ];
        "statamic.cp.collections.entries.reorder": [
            {
                name: "collection";
            }
        ];
        "statamic.cp.collections.entries.store": [
            {
                name: "collection";
            },
            {
                name: "site";
            }
        ];
        "statamic.cp.collections.entries.edit": [
            {
                name: "collection";
            },
            {
                name: "entry";
            }
        ];
        "statamic.cp.collections.entries.published.store": [
            {
                name: "collection";
            },
            {
                name: "entry";
            }
        ];
        "statamic.cp.collections.entries.published.destroy": [
            {
                name: "collection";
            },
            {
                name: "entry";
            }
        ];
        "statamic.cp.collections.entries.localize": [
            {
                name: "collection";
            },
            {
                name: "entry";
            }
        ];
        "statamic.cp.collections.entries.revisions.index": [
            {
                name: "collection";
            },
            {
                name: "entry";
            }
        ];
        "statamic.cp.collections.entries.revisions.store": [
            {
                name: "collection";
            },
            {
                name: "entry";
            }
        ];
        "statamic.cp.collections.entries.revisions.show": [
            {
                name: "collection";
            },
            {
                name: "entry";
            },
            {
                name: "revision";
            }
        ];
        "statamic.cp.collections.entries.restore-revision": [
            {
                name: "collection";
            },
            {
                name: "entry";
            }
        ];
        "statamic.cp.collections.entries.preview.edit": [
            {
                name: "collection";
            },
            {
                name: "entry";
            }
        ];
        "statamic.cp.collections.entries.preview.popout": [
            {
                name: "collection";
            },
            {
                name: "entry";
            }
        ];
        "statamic.cp.collections.entries.update": [
            {
                name: "collection";
            },
            {
                name: "entry";
            }
        ];
        "statamic.cp.taxonomies.index": [];
        "statamic.cp.taxonomies.create": [];
        "statamic.cp.taxonomies.store": [];
        "statamic.cp.taxonomies.show": [
            {
                name: "taxonomy";
            }
        ];
        "statamic.cp.taxonomies.edit": [
            {
                name: "taxonomy";
            }
        ];
        "statamic.cp.taxonomies.update": [
            {
                name: "taxonomy";
            }
        ];
        "statamic.cp.taxonomies.destroy": [
            {
                name: "taxonomy";
            }
        ];
        "statamic.cp.taxonomies.blueprints.index": [
            {
                name: "taxonomy";
            }
        ];
        "statamic.cp.taxonomies.blueprints.create": [
            {
                name: "taxonomy";
            }
        ];
        "statamic.cp.taxonomies.blueprints.store": [
            {
                name: "taxonomy";
            }
        ];
        "statamic.cp.taxonomies.blueprints.show": [
            {
                name: "taxonomy";
            },
            {
                name: "blueprint";
            }
        ];
        "statamic.cp.taxonomies.blueprints.edit": [
            {
                name: "taxonomy";
            },
            {
                name: "blueprint";
            }
        ];
        "statamic.cp.taxonomies.blueprints.update": [
            {
                name: "taxonomy";
            },
            {
                name: "blueprint";
            }
        ];
        "statamic.cp.taxonomies.blueprints.destroy": [
            {
                name: "taxonomy";
            },
            {
                name: "blueprint";
            }
        ];
        "statamic.cp.taxonomies.blueprints.reorder": [
            {
                name: "taxonomy";
            }
        ];
        "statamic.cp.taxonomies.terms.index": [
            {
                name: "taxonomy";
            }
        ];
        "statamic.cp.taxonomies.terms.actions.run": [
            {
                name: "taxonomy";
            }
        ];
        "statamic.cp.taxonomies.terms.actions.bulk": [
            {
                name: "taxonomy";
            }
        ];
        "statamic.cp.taxonomies.terms.create": [
            {
                name: "taxonomy";
            },
            {
                name: "site";
            }
        ];
        "statamic.cp.taxonomies.terms.preview.create": [
            {
                name: "taxonomy";
            },
            {
                name: "site";
            }
        ];
        "statamic.cp.taxonomies.terms.store": [
            {
                name: "taxonomy";
            },
            {
                name: "site";
            }
        ];
        "statamic.cp.taxonomies.terms.edit": [
            {
                name: "taxonomy";
            },
            {
                name: "term";
            },
            {
                name: "site";
            }
        ];
        "statamic.cp.taxonomies.terms.published.store": [
            {
                name: "taxonomy";
            },
            {
                name: "term";
            },
            {
                name: "site";
            }
        ];
        "statamic.cp.taxonomies.terms.published.destroy": [
            {
                name: "taxonomy";
            },
            {
                name: "term";
            },
            {
                name: "site";
            }
        ];
        "statamic.cp.taxonomies.terms.revisions.index": [
            {
                name: "taxonomy";
            },
            {
                name: "term";
            },
            {
                name: "site";
            }
        ];
        "statamic.cp.taxonomies.terms.revisions.store": [
            {
                name: "taxonomy";
            },
            {
                name: "term";
            },
            {
                name: "site";
            }
        ];
        "statamic.cp.taxonomies.terms.revisions.show": [
            {
                name: "taxonomy";
            },
            {
                name: "term";
            },
            {
                name: "site";
            },
            {
                name: "revision";
            }
        ];
        "statamic.cp.taxonomies.terms.restore-revision": [
            {
                name: "taxonomy";
            },
            {
                name: "term";
            },
            {
                name: "site";
            }
        ];
        "statamic.cp.taxonomies.terms.preview.edit": [
            {
                name: "taxonomy";
            },
            {
                name: "term";
            },
            {
                name: "site";
            }
        ];
        "statamic.cp.taxonomies.terms.preview.popout": [
            {
                name: "taxonomy";
            },
            {
                name: "term";
            },
            {
                name: "site";
            }
        ];
        "statamic.cp.taxonomies.terms.update": [
            {
                name: "taxonomy";
            },
            {
                name: "term";
            },
            {
                name: "site";
            }
        ];
        "statamic.cp.globals.index": [];
        "statamic.cp.globals.create": [];
        "statamic.cp.globals.store": [];
        "statamic.cp.globals.edit": [
            {
                name: "global_set";
            }
        ];
        "statamic.cp.globals.update": [
            {
                name: "global_set";
            }
        ];
        "statamic.cp.globals.destroy": [
            {
                name: "global_set";
            }
        ];
        "statamic.cp.globals.variables.edit": [
            {
                name: "global_set";
            }
        ];
        "statamic.cp.globals.variables.update": [
            {
                name: "global_set";
            }
        ];
        "statamic.cp.globals.blueprint.edit": [
            {
                name: "global_set";
            }
        ];
        "statamic.cp.globals.blueprint.update": [
            {
                name: "global_set";
            }
        ];
        "statamic.cp.asset-containers.index": [];
        "statamic.cp.asset-containers.create": [];
        "statamic.cp.asset-containers.store": [];
        "statamic.cp.asset-containers.show": [
            {
                name: "asset_container";
            }
        ];
        "statamic.cp.asset-containers.edit": [
            {
                name: "asset_container";
            }
        ];
        "statamic.cp.asset-containers.update": [
            {
                name: "asset_container";
            }
        ];
        "statamic.cp.asset-containers.destroy": [
            {
                name: "asset_container";
            }
        ];
        "statamic.cp.asset-containers.blueprint.edit": [
            {
                name: "asset_container";
            }
        ];
        "statamic.cp.asset-containers.blueprint.update": [
            {
                name: "asset_container";
            }
        ];
        "statamic.cp.assets.actions.run": [];
        "statamic.cp.assets.actions.bulk": [];
        "statamic.cp.assets.browse.index": [];
        "statamic.cp.assets.folders.actions.run": [
            {
                name: "asset_container";
            }
        ];
        "statamic.cp.assets.browse.edit": [
            {
                name: "asset_container";
            },
            {
                name: "path";
            }
        ];
        "statamic.cp.assets.browse.show": [
            {
                name: "asset_container";
            },
            {
                name: "path";
            }
        ];
        "statamic.cp.assets.index": [];
        "statamic.cp.assets.create": [];
        "statamic.cp.assets.store": [];
        "statamic.cp.assets.show": [
            {
                name: "encoded_asset";
            }
        ];
        "statamic.cp.assets.edit": [
            {
                name: "encoded_asset";
            }
        ];
        "statamic.cp.assets.update": [
            {
                name: "encoded_asset";
            }
        ];
        "statamic.cp.assets.destroy": [
            {
                name: "encoded_asset";
            }
        ];
        "statamic.cp.assets.download": [
            {
                name: "encoded_asset";
            }
        ];
        "statamic.cp.assets.thumbnails.show": [
            {
                name: "encoded_asset";
            },
            {
                name: "size";
            },
            {
                name: "orientation";
            }
        ];
        "statamic.cp.assets.svgs.show": [
            {
                name: "encoded_asset";
            }
        ];
        "statamic.cp.assets.pdfs.show": [
            {
                name: "encoded_asset";
            }
        ];
        "statamic.cp.fields.index": [];
        "statamic.cp.fields.edit": [];
        "statamic.cp.fields.update": [];
        "statamic.cp.fieldsets.index": [];
        "statamic.cp.fieldsets.create": [];
        "statamic.cp.fieldsets.store": [];
        "statamic.cp.fieldsets.edit": [
            {
                name: "fieldset";
            }
        ];
        "statamic.cp.fieldsets.update": [
            {
                name: "fieldset";
            }
        ];
        "statamic.cp.fieldsets.destroy": [
            {
                name: "fieldset";
            }
        ];
        "statamic.cp.blueprints.index": [];
        "statamic.cp.updater": [];
        "statamic.cp.updater.product": [
            {
                name: "product";
            }
        ];
        "statamic.cp.duplicates": [];
        "statamic.cp.duplicates.regenerate": [];
        "statamic.cp.addons.index": [];
        "statamic.cp.forms.actions.run": [];
        "statamic.cp.forms.actions.bulk": [];
        "statamic.cp.forms.submissions.actions.run": [
            {
                name: "form";
            }
        ];
        "statamic.cp.forms.submissions.actions.bulk": [
            {
                name: "form";
            }
        ];
        "statamic.cp.forms.index": [];
        "statamic.cp.forms.create": [];
        "statamic.cp.forms.store": [];
        "statamic.cp.forms.show": [
            {
                name: "form";
            }
        ];
        "statamic.cp.forms.edit": [
            {
                name: "form";
            }
        ];
        "statamic.cp.forms.update": [
            {
                name: "form";
            }
        ];
        "statamic.cp.forms.destroy": [
            {
                name: "form";
            }
        ];
        "statamic.cp.forms.submissions.index": [
            {
                name: "form";
            }
        ];
        "statamic.cp.forms.submissions.create": [
            {
                name: "form";
            }
        ];
        "statamic.cp.forms.submissions.store": [
            {
                name: "form";
            }
        ];
        "statamic.cp.forms.submissions.show": [
            {
                name: "form";
            },
            {
                name: "submission";
            }
        ];
        "statamic.cp.forms.submissions.edit": [
            {
                name: "form";
            },
            {
                name: "submission";
            }
        ];
        "statamic.cp.forms.submissions.update": [
            {
                name: "form";
            },
            {
                name: "submission";
            }
        ];
        "statamic.cp.forms.submissions.destroy": [
            {
                name: "form";
            },
            {
                name: "submission";
            }
        ];
        "statamic.cp.forms.export": [
            {
                name: "form";
            },
            {
                name: "type";
            }
        ];
        "statamic.cp.forms.blueprint.edit": [
            {
                name: "form";
            }
        ];
        "statamic.cp.forms.blueprint.update": [
            {
                name: "form";
            }
        ];
        "statamic.cp.users.actions.run": [];
        "statamic.cp.users.actions.bulk": [];
        "statamic.cp.users.blueprint.edit": [];
        "statamic.cp.users.blueprint.update": [];
        "statamic.cp.users.index": [];
        "statamic.cp.users.create": [];
        "statamic.cp.users.store": [];
        "statamic.cp.users.show": [
            {
                name: "user";
            }
        ];
        "statamic.cp.users.edit": [
            {
                name: "user";
            }
        ];
        "statamic.cp.users.update": [
            {
                name: "user";
            }
        ];
        "statamic.cp.users.destroy": [
            {
                name: "user";
            }
        ];
        "statamic.cp.users.password.update": [
            {
                name: "user";
            }
        ];
        "statamic.cp.account": [];
        "statamic.cp.user-groups.blueprint.edit": [];
        "statamic.cp.user-groups.blueprint.update": [];
        "statamic.cp.user-groups.index": [];
        "statamic.cp.user-groups.create": [];
        "statamic.cp.user-groups.store": [];
        "statamic.cp.user-groups.show": [
            {
                name: "user_group";
            }
        ];
        "statamic.cp.user-groups.edit": [
            {
                name: "user_group";
            }
        ];
        "statamic.cp.user-groups.update": [
            {
                name: "user_group";
            }
        ];
        "statamic.cp.user-groups.destroy": [
            {
                name: "user_group";
            }
        ];
        "statamic.cp.roles.index": [];
        "statamic.cp.roles.create": [];
        "statamic.cp.roles.store": [];
        "statamic.cp.roles.show": [
            {
                name: "role";
            }
        ];
        "statamic.cp.roles.edit": [
            {
                name: "role";
            }
        ];
        "statamic.cp.roles.update": [
            {
                name: "role";
            }
        ];
        "statamic.cp.roles.destroy": [
            {
                name: "role";
            }
        ];
        "statamic.cp.user.exists": [];
        "statamic.cp.search": [];
        "statamic.cp.utilities.index": [];
        "statamic.cp.utilities.cache": [];
        "statamic.cp.utilities.cache.clear": [
            {
                name: "cache";
            }
        ];
        "statamic.cp.utilities.cache.warm": [
            {
                name: "cache";
            }
        ];
        "statamic.cp.utilities.phpinfo": [];
        "statamic.cp.utilities.search": [];
        "statamic.cp.utilities.search.update": [];
        "statamic.cp.utilities.email": [];
        "statamic.cp.utilities.email.": [];
        "statamic.cp.utilities.licensing": [];
        "statamic.cp.utilities.licensing.refresh": [];
        "statamic.cp.utilities.logbook.show": [];
        "statamic.cp.utilities.logbook.destroy": [];
        "statamic.cp.relationship.index": [];
        "statamic.cp.relationship.data": [];
        "statamic.cp.relationship.filters": [];
        "statamic.cp.markdown.preview": [];
        "statamic.cp.files.upload": [];
        "statamic.cp.api.addons.index": [];
        "statamic.cp.api.addons.create": [];
        "statamic.cp.api.addons.store": [];
        "statamic.cp.api.addons.show": [
            {
                name: "addon";
            }
        ];
        "statamic.cp.api.addons.edit": [
            {
                name: "addon";
            }
        ];
        "statamic.cp.api.addons.update": [
            {
                name: "addon";
            }
        ];
        "statamic.cp.api.addons.destroy": [
            {
                name: "addon";
            }
        ];
        "statamic.cp.api.templates.index": [];
        "statamic.cp.api.templates.create": [];
        "statamic.cp.api.templates.store": [];
        "statamic.cp.api.templates.show": [
            {
                name: "template";
            }
        ];
        "statamic.cp.api.templates.edit": [
            {
                name: "template";
            }
        ];
        "statamic.cp.api.templates.update": [
            {
                name: "template";
            }
        ];
        "statamic.cp.api.templates.destroy": [
            {
                name: "template";
            }
        ];
        "statamic.cp.preferences.index": [];
        "statamic.cp.preferences.user.edit": [];
        "statamic.cp.preferences.user.update": [];
        "statamic.cp.preferences.role.edit": [
            {
                name: "role";
            }
        ];
        "statamic.cp.preferences.role.update": [
            {
                name: "role";
            }
        ];
        "statamic.cp.preferences.default.edit": [];
        "statamic.cp.preferences.default.update": [];
        "statamic.cp.preferences.store": [];
        "statamic.cp.preferences.destroy": [
            {
                name: "key";
            }
        ];
        "statamic.cp.preferences.nav.index": [];
        "statamic.cp.preferences.nav.user.edit": [];
        "statamic.cp.preferences.nav.user.update": [];
        "statamic.cp.preferences.nav.user.destroy": [];
        "statamic.cp.preferences.nav.role.edit": [
            {
                name: "role";
            }
        ];
        "statamic.cp.preferences.nav.role.update": [
            {
                name: "role";
            }
        ];
        "statamic.cp.preferences.nav.role.destroy": [
            {
                name: "role";
            }
        ];
        "statamic.cp.preferences.nav.default.edit": [];
        "statamic.cp.preferences.nav.default.update": [];
        "statamic.cp.preferences.nav.default.destroy": [];
        "statamic.cp.session.timeout": [];
        "statamic.cp.playground": [];
        "statamic.cp.404": [
            {
                name: "segments";
            }
        ];
        "statamic.forms.submit": [
            {
                name: "form";
            }
        ];
        "statamic.protect.password.show": [];
        "statamic.protect.password.store": [];
        "statamic.login": [];
        "statamic.logout": [];
        "statamic.register": [];
        "statamic.profile": [];
        "statamic.password": [];
        "statamic.password.email": [];
        "statamic.password.reset": [
            {
                name: "token";
            }
        ];
        "statamic.password.reset.action": [];
        "statamic.account.activate": [
            {
                name: "token";
            }
        ];
        "statamic.account.activate.action": [];
        "statamic.": [];
        "statamic.oauth.login": [
            {
                name: "provider";
            }
        ];
        "statamic.oauth.callback": [
            {
                name: "provider";
            }
        ];
    }
}
export {};
